//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.8.3928.0.
// 
namespace DayDoc.Objects.Xsd.Upd.ON_NSCHFDOPPR {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Файл {
        
        /// <remarks/>
        public ФайлСвУчДокОбор СвУчДокОбор;
        
        /// <remarks/>
        public ФайлДокумент Документ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдФайл;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлВерсФорм ВерсФорм;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВерсПрог;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлСвУчДокОбор {
        
        /// <remarks/>
        public ФайлСвУчДокОборСвОЭДОтпр СвОЭДОтпр;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдОтпр;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдПол;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлСвУчДокОборСвОЭДОтпр {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННЮЛ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдЭДО;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СумНДСТип {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("БезНДС", typeof(СумНДСТипБезНДС))]
        [System.Xml.Serialization.XmlElementAttribute("ДефНДС", typeof(СумНДСТипДефНДС))]
        [System.Xml.Serialization.XmlElementAttribute("СумНал", typeof(decimal))]
        public object Item;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum СумНДСТипБезНДС {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("без НДС")]
        безНДС,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum СумНДСТипДефНДС {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("-")]
        Item,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СумАкцизТип {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("БезАкциз", typeof(СумАкцизТипБезАкциз))]
        [System.Xml.Serialization.XmlElementAttribute("СумАкциз", typeof(decimal))]
        public object Item;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum СумАкцизТипБезАкциз {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("без акциза")]
        безакциза,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ТекстИнфТип {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Идентиф;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Значен;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ОснованиеТип {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОсн;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомОсн;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаОсн;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДопСвОсн;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдентОсн;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class КонтактТип {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Тлф;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ЭлПочта;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class АдрИнфТип {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодСтр;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string АдрТекст;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class АдрРФТип {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Индекс;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодРегион;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Район;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Город;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаселПункт;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Улица;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Дом;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Корпус;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Кварт;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class АдресТип {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("АдрИнф", typeof(АдрИнфТип))]
        [System.Xml.Serialization.XmlElementAttribute("АдрРФ", typeof(АдрРФТип))]
        [System.Xml.Serialization.XmlElementAttribute("КодГАР", typeof(string))]
        public object Item;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СвФЛТип {
        
        /// <remarks/>
        public ФИОТип ФИО;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ГосРегИПВыдДов;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННФЛ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФИОТип {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Фамилия;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Имя;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Отчество;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СвИПТип {
        
        /// <remarks/>
        public ФИОТип ФИО;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННФЛ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public СвИПТипДефИННФЛ ДефИННФЛ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ДефИННФЛSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СвГосРегИП;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum СвИПТипДефИННФЛ {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("-")]
        Item,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class УчастникТип {
        
        /// <remarks/>
        public УчастникТипИдСв ИдСв;
        
        /// <remarks/>
        public АдресТип Адрес;
        
        /// <remarks/>
        public КонтактТип Контакт;
        
        /// <remarks/>
        public УчастникТипБанкРекв БанкРекв;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОКПО;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СтруктПодр;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИнфДляУчаст;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КраткНазв;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class УчастникТипИдСв {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвИП", typeof(СвИПТип))]
        [System.Xml.Serialization.XmlElementAttribute("СвИнНеУч", typeof(УчастникТипИдСвСвИнНеУч))]
        [System.Xml.Serialization.XmlElementAttribute("СвФЛУчастФХЖ", typeof(СвФЛТип))]
        [System.Xml.Serialization.XmlElementAttribute("СвЮЛУч", typeof(УчастникТипИдСвСвЮЛУч))]
        public object Item;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class УчастникТипИдСвСвИнНеУч {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Идентиф;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class УчастникТипИдСвСвЮЛУч {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННЮЛ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public УчастникТипИдСвСвЮЛУчДефИННЮЛ ДефИННЮЛ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ДефИННЮЛSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КПП;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum УчастникТипИдСвСвЮЛУчДефИННЮЛ {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("-")]
        Item,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class УчастникТипБанкРекв {
        
        /// <remarks/>
        public УчастникТипБанкРеквСвБанк СвБанк;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерСчета;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class УчастникТипБанкРеквСвБанк {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимБанк;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string БИК;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КорСчет;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокумент {
        
        /// <remarks/>
        public ФайлДокументСвСчФакт СвСчФакт;
        
        /// <remarks/>
        public ФайлДокументТаблСчФакт ТаблСчФакт;
        
        /// <remarks/>
        public ФайлДокументСвПродПер СвПродПер;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Подписант")]
        public ФайлДокументПодписант[] Подписант;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументКНД КНД;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументФункция Функция;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ПоФактХЖ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимДокОпр;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаИнфПр;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВремИнфПр;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимЭконСубСост;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОснДоверОргСост;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СоглСтрДопИнф;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвСчФакт {
        
        /// <remarks/>
        public ФайлДокументСвСчФактИспрСчФ ИспрСчФ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвПрод")]
        public УчастникТип[] СвПрод;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ГрузОт")]
        public ФайлДокументСвСчФактГрузОт[] ГрузОт;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ГрузПолуч")]
        public УчастникТип[] ГрузПолуч;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвПРД")]
        public ФайлДокументСвСчФактСвПРД[] СвПРД;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвПокуп")]
        public УчастникТип[] СвПокуп;
        
        /// <remarks/>
        public ФайлДокументСвСчФактДопСвФХЖ1 ДопСвФХЖ1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ДокПодтвОтгр")]
        public ФайлДокументСвСчФактДокПодтвОтгр[] ДокПодтвОтгр;
        
        /// <remarks/>
        public ФайлДокументСвСчФактИнфПолФХЖ1 ИнфПолФХЖ1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерСчФ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаСчФ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодОКВ;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвСчФактИспрСчФ {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string НомИспрСчФ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументСвСчФактИспрСчФДефНомИспрСчФ ДефНомИспрСчФ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ДефНомИспрСчФSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаИспрСчФ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументСвСчФактИспрСчФДефДатаИспрСчФ ДефДатаИспрСчФ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ДефДатаИспрСчФSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ФайлДокументСвСчФактИспрСчФДефНомИспрСчФ {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("-")]
        Item,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ФайлДокументСвСчФактИспрСчФДефДатаИспрСчФ {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("-")]
        Item,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвСчФактГрузОт {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ГрузОтпр", typeof(УчастникТип))]
        [System.Xml.Serialization.XmlElementAttribute("ОнЖе", typeof(ФайлДокументСвСчФактГрузОтОнЖе))]
        public object Item;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ФайлДокументСвСчФактГрузОтОнЖе {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("он же")]
        онже,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвСчФактСвПРД {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерПРД;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаПРД;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СуммаПРД;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СуммаПРДSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвСчФактДопСвФХЖ1 {
        
        /// <remarks/>
        public ФайлДокументСвСчФактДопСвФХЖ1ИнфПродГосЗакКазн ИнфПродГосЗакКазн;
        
        /// <remarks/>
        public УчастникТип СвФактор;
        
        /// <remarks/>
        public ОснованиеТип ОснУстДенТреб;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдГосКон;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОКВ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal КурсВал;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool КурсВалSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументСвСчФактДопСвФХЖ1ОбстФормСЧФ ОбстФормСЧФ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ОбстФормСЧФSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвСчФактДопСвФХЖ1ИнфПродГосЗакКазн {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаГосКонт;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерГосКонт;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ЛицСчетПрод;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодПродБюджКласс;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодЦелиПрод;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодКазначПрод;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимКазначПрод;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ФайлДокументСвСчФактДопСвФХЖ1ОбстФормСЧФ {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвСчФактДокПодтвОтгр {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимДокОтгр;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомДокОтгр;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаДокОтгр;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвСчФактИнфПолФХЖ1 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ТекстИнф")]
        public ТекстИнфТип[] ТекстИнф;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдФайлИнфПол;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументТаблСчФакт {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведТов")]
        public ФайлДокументТаблСчФактСведТов[] СведТов;
        
        /// <remarks/>
        public ФайлДокументТаблСчФактВсегоОпл ВсегоОпл;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументТаблСчФактСведТов {
        
        /// <remarks/>
        public СумАкцизТип Акциз;
        
        /// <remarks/>
        public СумНДСТип СумНал;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвТД")]
        public ФайлДокументТаблСчФактСведТовСвТД[] СвТД;
        
        /// <remarks/>
        public ФайлДокументТаблСчФактСведТовДопСведТов ДопСведТов;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ИнфПолФХЖ2")]
        public ТекстИнфТип[] ИнфПолФХЖ2;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string НомСтр;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимТов;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОКЕИ_Тов;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументТаблСчФактСведТовДефОКЕИ_Тов ДефОКЕИ_Тов;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ДефОКЕИ_ТовSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal КолТов;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool КолТовSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ЦенаТов;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ЦенаТовSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СтТовБезНДС;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СтТовБезНДСSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументТаблСчФактСведТовНалСт НалСт;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СтТовУчНал;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СтТовУчНалSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументТаблСчФактСведТовДефСтТовУчНал ДефСтТовУчНал;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ДефСтТовУчНалSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументТаблСчФактСведТовСвТД {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодПроисх;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументТаблСчФактСведТовСвТДДефКодПроисх ДефКодПроисх;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ДефКодПроисхSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерТД;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ФайлДокументТаблСчФактСведТовСвТДДефКодПроисх {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("-")]
        Item,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументТаблСчФактСведТовДопСведТов {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведПрослеж")]
        public ФайлДокументТаблСчФактСведТовДопСведТовСведПрослеж[] СведПрослеж;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("НомСредИдентТов")]
        public ФайлДокументТаблСчФактСведТовДопСведТовНомСредИдентТов[] НомСредИдентТов;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументТаблСчФактСведТовДопСведТовПрТовРаб ПрТовРаб;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ПрТовРабSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДопПризн;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимЕдИзм;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КрНаимСтрПр;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal НадлОтп;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool НадлОтпSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ХарактерТов;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СортТов;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string АртикулТов;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодТов;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодКат;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодВидТов;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументТаблСчФактСведТовДопСведТовСведПрослеж {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомТовПрослеж;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ЕдИзмПрослеж;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимЕдИзмПрослеж;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal КолВЕдПрослеж;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДопПрослеж;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументТаблСчФактСведТовДопСведТовНомСредИдентТов {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("КИЗ", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("НомУпак", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public string[] Items;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдентТрансУпак;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        КИЗ,
        
        /// <remarks/>
        НомУпак,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ФайлДокументТаблСчФактСведТовДопСведТовПрТовРаб {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ФайлДокументТаблСчФактСведТовДефОКЕИ_Тов {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("-")]
        Item,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ФайлДокументТаблСчФактСведТовНалСт {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0%")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10%")]
        Item10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("18%")]
        Item18,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20%")]
        Item20,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10/110")]
        Item10110,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("18/118")]
        Item18118,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20/120")]
        Item20120,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("без НДС")]
        безНДС,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("НДС исчисляется налоговым агентом")]
        НДСисчисляетсяналоговымагентом,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ФайлДокументТаблСчФактСведТовДефСтТовУчНал {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("-")]
        Item,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументТаблСчФактВсегоОпл {
        
        /// <remarks/>
        public СумНДСТип СумНалВсего;
        
        /// <remarks/>
        public decimal КолНеттоВс;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool КолНеттоВсSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СтТовБезНДСВсего;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СтТовБезНДСВсегоSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СтТовУчНалВсего;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СтТовУчНалВсегоSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументТаблСчФактВсегоОплДефСтТовУчНалВсего ДефСтТовУчНалВсего;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ДефСтТовУчНалВсегоSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ФайлДокументТаблСчФактВсегоОплДефСтТовУчНалВсего {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("-")]
        Item,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвПродПер {
        
        /// <remarks/>
        public ФайлДокументСвПродПерСвПер СвПер;
        
        /// <remarks/>
        public ФайлДокументСвПродПерИнфПолФХЖ3 ИнфПолФХЖ3;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвПродПерСвПер {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ОснПер")]
        public ОснованиеТип[] ОснПер;
        
        /// <remarks/>
        public ФайлДокументСвПродПерСвПерСвЛицПер СвЛицПер;
        
        /// <remarks/>
        public ФайлДокументСвПродПерСвПерТранГруз ТранГруз;
        
        /// <remarks/>
        public ФайлДокументСвПродПерСвПерСвПерВещи СвПерВещи;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СодОпер;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВидОпер;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаПер;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаНач;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаОкон;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвПродПерСвПерСвЛицПер {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ИнЛицо", typeof(ФайлДокументСвПродПерСвПерСвЛицПерИнЛицо))]
        [System.Xml.Serialization.XmlElementAttribute("РабОргПрод", typeof(ФайлДокументСвПродПерСвПерСвЛицПерРабОргПрод))]
        public object Item;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвПродПерСвПерСвЛицПерИнЛицо {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ПредОргПер", typeof(ФайлДокументСвПродПерСвПерСвЛицПерИнЛицоПредОргПер))]
        [System.Xml.Serialization.XmlElementAttribute("ФЛПер", typeof(ФайлДокументСвПродПерСвПерСвЛицПерИнЛицоФЛПер))]
        public object Item;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвПродПерСвПерСвЛицПерИнЛицоПредОргПер {
        
        /// <remarks/>
        public ФИОТип ФИО;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Должность;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОргПер;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОснДоверОргПер;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОснПолнПредПер;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвПродПерСвПерСвЛицПерИнЛицоФЛПер {
        
        /// <remarks/>
        public ФИОТип ФИО;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОснДоверФЛ;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвПродПерСвПерСвЛицПерРабОргПрод {
        
        /// <remarks/>
        public ФИОТип ФИО;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Должность;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОснПолн;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвПродПерСвПерТранГруз {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ТранНакл")]
        public ФайлДокументСвПродПерСвПерТранГрузТранНакл[] ТранНакл;
        
        /// <remarks/>
        public УчастникТип Перевозчик;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СвТранГруз;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвПродПерСвПерТранГрузТранНакл {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомТранНакл;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаТранНакл;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвПродПерСвПерСвПерВещи {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаПерВещ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СвПерВещ;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвПродПерИнфПолФХЖ3 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ТекстИнф")]
        public ТекстИнфТип[] ТекстИнф;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдФайлИнфПол;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументПодписант {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ИП", typeof(СвИПТип))]
        [System.Xml.Serialization.XmlElementAttribute("ФЛ", typeof(СвФЛТип))]
        [System.Xml.Serialization.XmlElementAttribute("ЮЛ", typeof(ФайлДокументПодписантЮЛ))]
        public object Item;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументПодписантОблПолн ОблПолн;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументПодписантСтатус Статус;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОснПолн;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОснПолнОрг;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументПодписантЮЛ {
        
        /// <remarks/>
        public ФИОТип ФИО;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ГосРегИПВыдДов;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННЮЛ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Должн;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ФайлДокументПодписантОблПолн {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ФайлДокументПодписантСтатус {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ФайлДокументКНД {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1115131")]
        Item1115131,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ФайлДокументФункция {
        
        /// <remarks/>
        СЧФ,
        
        /// <remarks/>
        СЧФДОП,
        
        /// <remarks/>
        ДОП,
        
        /// <remarks/>
        СвРК,
        
        /// <remarks/>
        СвЗК,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ФайлВерсФорм {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5.01")]
        Item501,
    }
}
