//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.8.3928.0.
// 
namespace DayDoc.Objects.Xsd.Act.DP_REZRUISP {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Файл {
        
        /// <remarks/>
        public ФайлСвУчДокОбор СвУчДокОбор;
        
        /// <remarks/>
        public ФайлДокумент Документ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдФайл;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВерсПрог;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлВерсФорм ВерсФорм;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлСвУчДокОбор {
        
        /// <remarks/>
        public ФайлСвУчДокОборСвОЭДОтпр СвОЭДОтпр;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдОтпр;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдПол;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлСвУчДокОборСвОЭДОтпр {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННЮЛ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдЭДО;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ТекстИнфТип {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Идентиф;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Значен;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class КонтактТип {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Тлф;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ЭлПочта;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class АдрИнфТип {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодСтр;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string АдрТекст;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class АдрРФТип {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Индекс;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодРегион;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Район;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Город;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаселПункт;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Улица;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Дом;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Корпус;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Кварт;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class АдресТип {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("АдрИно", typeof(АдрИнфТип))]
        [System.Xml.Serialization.XmlElementAttribute("АдрРФ", typeof(АдрРФТип))]
        [System.Xml.Serialization.XmlElementAttribute("КодГАР", typeof(string))]
        public object Item;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СвИПТип {
        
        /// <remarks/>
        public ФИОТип ФИО;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННФЛ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СвГосРегИП;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФИОТип {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Фамилия;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Имя;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Отчество;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СвФлТип {
        
        /// <remarks/>
        public ФИОТип ФИО;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННФЛ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class УчастникТип {
        
        /// <remarks/>
        public УчастникТипИдСв ИдСв;
        
        /// <remarks/>
        public АдресТип Адрес;
        
        /// <remarks/>
        public КонтактТип Контакт;
        
        /// <remarks/>
        public УчастникТипБанкРекв БанкРекв;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОКПО;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СтруктПодр;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИнфДляУчаст;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class УчастникТипИдСв {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвИП", typeof(СвИПТип))]
        [System.Xml.Serialization.XmlElementAttribute("СвОрг", typeof(УчастникТипИдСвСвОрг))]
        [System.Xml.Serialization.XmlElementAttribute("СвФЛ", typeof(СвФлТип))]
        public object Item;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class УчастникТипИдСвСвОрг {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ИнОрг", typeof(УчастникТипИдСвСвОргИнОрг))]
        [System.Xml.Serialization.XmlElementAttribute("СвЮЛ", typeof(УчастникТипИдСвСвОргСвЮЛ))]
        public object Item;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class УчастникТипИдСвСвОргИнОрг {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Страна;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class УчастникТипИдСвСвОргСвЮЛ {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННЮЛ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КПП;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class УчастникТипБанкРекв {
        
        /// <remarks/>
        public УчастникТипБанкРеквСвБанк СвБанк;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерСчета;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class УчастникТипБанкРеквСвБанк {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимБанк;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string БИК;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КорСчет;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокумент {
        
        /// <remarks/>
        public ФайлДокументСвДокПРУ СвДокПРУ;
        
        /// <remarks/>
        public ФайлДокументСодФХЖ2 СодФХЖ2;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Подписант")]
        public ФайлДокументПодписант[] Подписант;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументКНД КНД;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаИнфИсп;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВремИнфИсп;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимЭконСубСост;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОснДоверОргСост;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвДокПРУ {
        
        /// <remarks/>
        public ФайлДокументСвДокПРУНаимДок НаимДок;
        
        /// <remarks/>
        public ФайлДокументСвДокПРУИдентДок ИдентДок;
        
        /// <remarks/>
        public ФайлДокументСвДокПРУИспрДокПРУ ИспрДокПРУ;
        
        /// <remarks/>
        public ФайлДокументСвДокПРУДенИзм ДенИзм;
        
        /// <remarks/>
        public ФайлДокументСвДокПРУСодФХЖ1 СодФХЖ1;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвДокПРУНаимДок {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументСвДокПРУНаимДокПоФактХЖ ПоФактХЖ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимДокОпр;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ФайлДокументСвДокПРУНаимДокПоФактХЖ {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Документ о передаче результатов работ (Документ об оказании услуг)")]
        ДокументопередачерезультатовработДокументобоказанииуслуг,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвДокПРУИдентДок {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомДокПРУ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаДокПРУ;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвДокПРУИспрДокПРУ {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string НомИспрДокПРУ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаИспрДокПРУ;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвДокПРУДенИзм {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодОКВ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОКВ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal КурсВал;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool КурсВалSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвДокПРУСодФХЖ1 {
        
        /// <remarks/>
        public string ЗагСодОпер;
        
        /// <remarks/>
        public УчастникТип Исполнитель;
        
        /// <remarks/>
        public УчастникТип Заказчик;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Основание")]
        public ФайлДокументСвДокПРУСодФХЖ1Основание[] Основание;
        
        /// <remarks/>
        public string ИдГосКон;
        
        /// <remarks/>
        public string ВидОперации;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ОписРабот")]
        public ФайлДокументСвДокПРУСодФХЖ1ОписРабот[] ОписРабот;
        
        /// <remarks/>
        public ФайлДокументСвДокПРУСодФХЖ1ИнфПолФХЖ1 ИнфПолФХЖ1;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвДокПРУСодФХЖ1Основание {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОсн;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомОсн;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаОсн;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДопСвОсн;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвДокПРУСодФХЖ1ОписРабот {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Работа")]
        public ФайлДокументСвДокПРУСодФХЖ1ОписРаботРабота[] Работа;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НачРабот;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КонРабот;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СтБезНДСИт;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СтБезНДСИтSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СумНДСИт;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СумНДСИтSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СтУчНДСИт;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвДокПРУСодФХЖ1ОписРаботРабота {
        
        /// <remarks/>
        public string Описание;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ИнфПолеОписРабот")]
        public ТекстИнфТип[] ИнфПолеОписРабот;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Номер;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимРабот;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимЕдИзм;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОКЕИ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Цена;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ЦенаSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Количество;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool КоличествоSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СтоимБезНДС;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СтоимБезНДСSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументСвДокПРУСодФХЖ1ОписРаботРаботаНалСт НалСт;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool НалСтSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СумНДС;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СумНДСSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СтоимУчНДС;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СтоимУчНДСSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КоррСчДебет;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КоррСчКредит;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ФайлДокументСвДокПРУСодФХЖ1ОписРаботРаботаНалСт {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0%")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10%")]
        Item10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("18%")]
        Item18,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20%")]
        Item20,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10/110")]
        Item10110,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("18/118")]
        Item18118,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20/120")]
        Item20120,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("без НДС")]
        безНДС,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвДокПРУСодФХЖ1ИнфПолФХЖ1 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ТекстИнф")]
        public ТекстИнфТип[] ТекстИнф;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдФайлИнфПол;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСодФХЖ2 {
        
        /// <remarks/>
        public ФайлДокументСодФХЖ2СвПерВещи СвПерВещи;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ИнфПолФХЖ2")]
        public ТекстИнфТип[] ИнфПолФХЖ2;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СодОпер;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаПер;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСодФХЖ2СвПерВещи {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаПерВещ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СвПерВещ;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументПодписант {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ИП", typeof(СвИПТип))]
        [System.Xml.Serialization.XmlElementAttribute("ФЛ", typeof(СвФлТип))]
        [System.Xml.Serialization.XmlElementAttribute("ЮЛ", typeof(ФайлДокументПодписантЮЛ))]
        public object Item;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументПодписантОблПолн ОблПолн;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументПодписантСтатус Статус;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОснПолнПодп;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОснПолнОрг;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументПодписантЮЛ {
        
        /// <remarks/>
        public ФИОТип ФИО;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННЮЛ;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Должн;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ФайлДокументПодписантОблПолн {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ФайлДокументПодписантСтатус {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ФайлДокументКНД {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1175012")]
        Item1175012,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ФайлВерсФорм {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5.02")]
        Item502,
    }
}
